-- Users table
CREATE TABLE users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(80) NOT NULL,
    LastName VARCHAR(80) NOT NULL,
    Email VARCHAR(120) NOT NULL UNIQUE,
    PasswordHash VARCHAR(200) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Organizations table
CREATE TABLE organizations (
    OrgID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrgName VARCHAR(120) NOT NULL UNIQUE,
    Description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Memberships table
CREATE TABLE memberships (
    MembershipID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    OrgID INTEGER NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    DateApplied DATETIME DEFAULT CURRENT_TIMESTAMP,
    DateApproved DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (OrgID) REFERENCES organizations(OrgID) ON DELETE CASCADE
);

-- OfficerRoles table
CREATE TABLE officer_roles (
    OfficerRoleID INTEGER PRIMARY KEY AUTOINCREMENT,
    MembershipID INTEGER NOT NULL,
    RoleName VARCHAR(50) NOT NULL,
    StartDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    EndDate DATETIME,
    -- Permission flags: 0 = false, 1 = true
    can_post_announcements INTEGER DEFAULT 0,
    can_create_events INTEGER DEFAULT 0,
    can_approve_members INTEGER DEFAULT 0,
    can_assign_roles INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MembershipID) REFERENCES memberships(MembershipID) ON DELETE CASCADE
);

-- Announcements table
CREATE TABLE announcements (
    AnnouncementID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrgID INTEGER NOT NULL,
    CreatedBy INTEGER NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    Attachments TEXT,
    DatePosted DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrgID) REFERENCES organizations(OrgID) ON DELETE CASCADE,
    FOREIGN KEY (CreatedBy) REFERENCES officer_roles(OfficerRoleID) ON DELETE CASCADE
);

-- Events table
CREATE TABLE events (
    EventID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrgID INTEGER NOT NULL,
    CreatedBy INTEGER NOT NULL,
    EventName VARCHAR(200) NOT NULL,
    Description TEXT,
    EventDate DATETIME,
    Location VARCHAR(200),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrgID) REFERENCES organizations(OrgID) ON DELETE CASCADE,
    FOREIGN KEY (CreatedBy) REFERENCES officer_roles(OfficerRoleID) ON DELETE CASCADE
);